CinemaAppWorkshopsRepo/CinemaApp.Web/Controllers/CinemaController.cs
namespace CinemaApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Services.Data.Interfaces;
    using ViewModels.Cinema;

    public class CinemaController : BaseController
    {
        private readonly ICinemaService cinemaService;

        public CinemaController(ICinemaService cinemaService, IManagerService managerService)
            : base(managerService)
        {
            this.cinemaService = cinemaService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            bool isManager = await this.IsUserManagerAsync();
            if (isManager)
            {
                return this.RedirectToAction(nameof(Manage));
            }

            IEnumerable<CinemaIndexViewModel> cinemas =
                await this.cinemaService.IndexGetAllOrderedByLocationAsync();

            return this.View(cinemas);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string? id)
        {
            bool isManager = await this.IsUserManagerAsync();
            if (isManager)
            {
                return this.RedirectToAction(nameof(Manage));
            }

            Guid cinemaGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id, ref cinemaGuid);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            CinemaDetailsViewModel? viewModel = await this.cinemaService
                .GetCinemaDetailsByIdAsync(cinemaGuid);

            if (viewModel == null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> ViewProgram(Guid id)
        {
            bool isManager = await this.IsUserManagerAsync();
            if (isManager)
            {
                return this.RedirectToAction(nameof(Manage));
            }

            CinemaProgramViewModel? viewModel = await this.cinemaService.GetCinemaProgramByIdAsync(id);

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Manage()
        {
            IEnumerable<CinemaIndexViewModel> cinemas =
                await this.cinemaService.IndexGetAllOrderedByLocationAsync();

            return this.View(cinemas);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Create(AddCinemaFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.cinemaService.AddCinemaAsync(model);

            return this.RedirectToAction(nameof(Manage));
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(string? id)
        {
            Guid cinemaGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id, ref cinemaGuid);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Manage));
            }

            EditCinemaFormModel? formModel = await this.cinemaService
                .GetCinemaForEditByIdAsync(cinemaGuid);

            return this.View(formModel);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(EditCinemaFormModel formModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(formModel);
            }

            bool isUpdated = await this.cinemaService
                .EditCinemaAsync(formModel);
            if (!isUpdated)
            {
                ModelState.AddModelError(string.Empty, "Unexpected error occurred while updating the cinema! Please contact administrator");
                return this.View(formModel);
            }

            return this.RedirectToAction(nameof(Manage));
        }
    }
}

CinemaAppWorkshopsRepo/CinemaApp.Web/Controllers/MovieController.cs
namespace CinemaApp.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Services.Data.Interfaces;
    using ViewModels.Movie;

    using static Common.EntityValidationConstants.Movie;

    public class MovieController : BaseController
    {
        private readonly IMovieService movieService;

        public MovieController(IMovieService movieService, IManagerService managerService)
            : base(managerService)
        {
            this.movieService = movieService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index(string? searchQuery = null, string? genre = null, int? releaseYear = null, int pageNumber = 1)
        {
            bool isManager = await this.IsUserManagerAsync();
            if (isManager)
            {
                return this.RedirectToAction(nameof(Manage));
            }

            (IEnumerable<AllMoviesIndexViewModel> movies, int totalPages) =
                await this.movieService.GetAllMoviesAsync(searchQuery, genre, releaseYear, pageNumber);

            ViewData["SearchQuery"] = searchQuery;
            ViewData["Genre"] = genre;
            ViewData["ReleaseYear"] = releaseYear;
            ViewData["CurrentPage"] = pageNumber;
            ViewData["TotalPages"] = totalPages;

            return this.View(movies);
        }




        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(string? id)
        {
            bool isManager = await this.IsUserManagerAsync();
            if (isManager)
            {
                return this.RedirectToAction(nameof(Manage));
            }

            Guid movieGuid = Guid.Empty;
            bool isGuidValid = this.IsGuidValid(id, ref movieGuid);
            if (!isGuidValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            MovieDetailsViewModel? movie = await this.movieService
                .GetMovieDetailsByIdAsync(movieGuid);
            if (movie == null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            return this.View(movie);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Manage()
        {
            IEnumerable<AllMoviesIndexViewModel> allMovies =
                await this.movieService.GetAllMoviesAsync();

            return this.View(allMovies);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Create(AddMovieInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            bool result = await this.movieService.AddMovieAsync(inputModel);
            if (!result)
            {
                this.ModelState.AddModelError(nameof(inputModel.ReleaseDate),
                    String.Format("The Release Date must be in the following format: {0}", ReleaseDateFormat));
                return this.View(inputModel);
            }

            return this.RedirectToAction(nameof(Manage));
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AddToProgram(string? id)
        {
            Guid movieGuid = Guid.Empty;
            bool isGuidValid = this.IsGuidValid(id, ref movieGuid);
            if (!isGuidValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            AddMovieToCinemaInputModel? viewModel = await this.movieService
                .GetAddMovieToCinemaInputModelByIdAsync(movieGuid);
            if (viewModel == null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AddToProgram(AddMovieToCinemaInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            Guid movieGuid = Guid.Empty;
            bool isGuidValid = this.IsGuidValid(model.Id, ref movieGuid);
            if (!isGuidValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            bool result = await this.movieService
                .AddMovieToCinemasAsync(movieGuid, model);
            if (!result)
            {
                return this.RedirectToAction(nameof(Index));
            }

            return this.RedirectToAction(nameof(Manage));
        }
    }
}

CinemaAppWorkshopsRepo/CinemaApp.Web/Controllers/TicketController.cs
namespace CinemaApp.Web.Controllers
{
    using CinemaApp.Web.Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Services.Data.Interfaces;
    using ViewModels.Tickets;

    public class TicketController : BaseController
    {
        private readonly ITicketService ticketService;
        private readonly ICinemaService cinemaService;

        public TicketController(ITicketService ticketService, ICinemaService cinemaService, IManagerService managerService)
            : base(managerService)
        {
            this.ticketService = ticketService;
            this.cinemaService = cinemaService;
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyTickets()
        {
            string userId = this.User.GetUserId();
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Index", "Home");
            }

            Guid userGuid = Guid.Parse(userId);
            var tickets = await this.ticketService.GetUserTicketsAsync(userGuid);

            return View(tickets);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Manage()
        {
            var cinemas = await this.cinemaService.IndexGetAllOrderedByLocationAsync();
            return View(cinemas);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public IActionResult SetAvailableTickets(Guid cinemaId, Guid movieId)
        {
            var viewModel = new SetAvailableTicketsViewModel
            {
                CinemaId = cinemaId,
                MovieId = movieId
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> SetAvailableTickets(SetAvailableTicketsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            bool result = await this.ticketService.SetAvailableTicketsAsync(model);
            if (!result)
            {
                ModelState.AddModelError(string.Empty, "Unable to set available tickets. Please try again.");
                return View(model);
            }

            return RedirectToAction(nameof(Manage));
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public IActionResult BuyTicket(Guid cinemaId, Guid movieId)
        {
            string userId = this.User.GetUserId();
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Index", "Home");
            }

            var viewModel = new BuyTicketViewModel
            {
                CinemaId = cinemaId,
                MovieId = movieId,
                UserId = Guid.Parse(userId)
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> BuyTicket(BuyTicketViewModel model)
        {
            string userId = this.User.GetUserId();
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Guid userGuid = Guid.Parse(userId);
            bool result = await this.ticketService.BuyTicketAsync(model, userGuid);
            if (!result)
            {
                ModelState.AddModelError(string.Empty, "Unable to buy ticket. Please try again.");
                return View(model);
            }

            return RedirectToAction(nameof(MyTickets));
        }
    }
}

CinemaAppWorkshopsRepo/CinemaApp.Web/Views/Shared/_Layout.cshtml
@using CinemaApp.Services.Data.Interfaces
@using CinemaApp.Web.Infrastructure.Extensions
@using static CinemaApp.Common.ApplicationConstants

@inject IManagerService managerService
@{
    int currentYear = DateTime.UtcNow.Year;
    string footerNote = (ReleaseYear == currentYear) ?
        $"{currentYear}" : $"{ReleaseYear} - {currentYear}";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaApp.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CinemaWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (this.User?.Identity?.IsAuthenticated ?? false)
                        {
                            if (await this.managerService.IsUserManagerAsync(this.User.GetUserId()))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="managerDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Manager
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="managerDropdown">
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="Cinema" asp-action="Manage">Manage Cinemas</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="Movie" asp-action="Manage">Manage Movies</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="Ticket" asp-action="Manage">Manage Tickets</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Watchlist" asp-action="Index">Watchlist</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>&copy; @footerNote CinemaWebApp | Bringing Cinema and Movies to You</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/buyTickets.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>